Adjust flow

diff --git a/ops/bin/configure b/ops/bin/configure
--- a/ops/bin/configure
+++ b/ops/bin/configure
@@ -1,20 +1,28 @@
 #!/bin/bash
 
+clear
 set -e
 
 CONFIG_TEMP='/config/~TEMP_api.env~'
 CONFIG_REAL='/config/api.env'
 
+echo -e '\n===== CURRENT VERSION: =====\n\033[0;31m'
+cat $CONFIG_REAL
+echo -e '\033[0m\n============================\n'
+
+read -p $'Type \033[0;36myes\033[0m to edit: ' -r
+echo
+if [[ ! "$REPLY" == "yes" ]]; then
+	echo "Aborted."
+	exit 1
+fi
+
 cp -f $CONFIG_REAL $CONFIG_TEMP
 nano $CONFIG_TEMP
 
-clear
-echo 'Please review your changes (\033[0;31mold\033[0m/\033[0;32mnew\033[0m)'
-echo -e '\n\n\033[0;31m'
-cat $CONFIG_REAL
-echo -e '\n\n\033[0;32m'
+echo -e '\n===== YOUR CHANGES: =====\n\033[0;32m'
 cat $CONFIG_TEMP
-echo -e '\033[0m'
+echo -e '\033[0m\n============================\n'
 
 read -p $'Type \033[0;36myes\033[0m to apply changes: ' -r
 echo
